import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { Header } from "@/components";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Rafael Lopez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
      </head>
      <body
        className={`${GeistSans.className} bg-[url('/bg-ruido.png')] select-none`}
      >
        <main className="px-5 min-h-[90dvh] gap-4 flex flex-col items-center select-none">
          <Header />
          <Navigation />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
